ALTER TABLE boats ADD COLUMN IF NOT EXISTS photo_link TEXT;
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/65kxfiw1bdx4nna9vu6or/AIDwbI3dhgLMVl_DN3Vztfw?rlkey=nfxhme61shs2ypsxlmodls6i4&st=md4h0lvu&dl=0' WHERE name = '44FT SEA RAY SUNDANCER';
UPDATE boats SET photo_link = 'https://ar-visuals.aryeo.com/sites/2215-nw-14th-st-miami-fl-33125-18032021/branded' WHERE name = '67FT AICON';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/vhmsr3ihh9wnxaru1z2og/AKSUZf8bb-ZyPDb6UPFS7Ng?rlkey=r6wyiczer8smi1wwii9okk8zk&st=gk7xiggr&dl=0' WHERE name = '50FT SUNSEEKER MANHATTAN';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1-_-ppr6rmZGPrfe2kr73rnwfTDScQ1uK' WHERE name = '60FT Absolute – “Disco”';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1t0ah2ohUVpR76tCQosnz9yWlkmTOzFf_?usp=sharing' WHERE name = '102FT LEOPARD SPORT';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/ya2ft7ehbbiuq0hxrazeu/ALNx8y7-f78oAMDq_md5q08?rlkey=xs369x14vp2wamwrct1qfriok&st=2seb4eli&dl=0' WHERE name = '26FT SEA RAY SUNDECK';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/4gedjmhzt0o1us457gx8q/AOFdPABFbDorQ8ceHTyEayQ?rlkey=110elk7sqmg3tu04x9jcpj29j&st=ysh2pne0&dl=0' WHERE name = '37FT SUNDANCER';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/t9k40sskywazktg9zgbvb/AO26Ueh-MgfcrB3NAckP7Uw?rlkey=tpf9s29lnyyd36bs7sojmtf7e&st=xa7zzdqx&dl=0' WHERE name = '42FT REGAL';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/fy50pz12s2rvceujky1rq/AJUeZ939B-2Usl7DYaw7E34?rlkey=bx3uygx3fa05f0zvcqfd65rb4&st=9k1c668x&dl=0' WHERE name = '37FT MONTERREY BLUE';
UPDATE boats SET photo_link = 'https://share.google/MQwd4XYx1mozzalkx' WHERE name = '55FT AZIMUT “PINK PANTHER”';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/6i3murr22nv09z61vhwf3/AK2ZV39ehhoppeQ0r-b4hSU?rlkey=xvi233a24kc7y89tw7q9ipbcw&st=binvxv7p&dl=0' WHERE name = '47FT WELLCRAFT';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/193hJhzFA072vUfXN-IMyQdeSNaYAvtmP' WHERE name = '60FT HATTERAS';
UPDATE boats SET photo_link = 'https://yachtscollection.pixieset.com/rodman60familyadventure/' WHERE name = '60FT Rodman Family Adventures';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/5g7nta3aob4696j4lj6yx/AN-4D_f3DNbvqTPlcWi9xxA?rlkey=88a3t2p8h5uvvqwqz3xgp4rh8&st=renxhn4m&dl=0' WHERE name = '78FT NUMARINE “HAPPY ENDING”';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/x558ivjvuyqvnp8nlc5fm/ANZ9VHHWoZaty8C1Vo5jrIA?rlkey=s4o4bop0hbfalv1paxo588bay&st=2u01qm7u&dl=0' WHERE name = '30FT Hurricane Sundeck';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/zoldjzyzd6scqj86waegr/ADuFfYoAuxCbmAIa3Td42do?rlkey=trbmlxn2r32meodsi3oeh06hw&st=lzgf21mk&dl=0' WHERE name = '53FT AZIMUT';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/u0lngiscceb987bsar6ma/ANAFkjdRuHrumsbu-zYoBnU?rlkey=xr15967zrrzbzpyotbuaw9cwr&st=9wc7oo7u&dl=0' WHERE name = '48FT CRANCHI';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/98383l68zwwuds1znt07g/AOy-Hu5EMQ-AsPavDGxwtcE?rlkey=ojb5jg7plkcgaa99amqpnslad&e=1&st=2rkjvzlu&dl=0' WHERE name = '30FT DAZE';
UPDATE boats SET photo_link = 'https://pixies.et/LVSWmcs8' WHERE name = '50FT Sea Ray “PINK Last Fling"';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/m0778jbyraq2l8qbjbwkc/AAcBo2ulkLBuoTWrXFh0MiM?rlkey=qgdw6imhmeaqcfgevisvnju4o&st=hhoqsmb3&dl=0' WHERE name = '46FT PINK MAXUM';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/abzce06uqdm7ao0lbfy8j/AENtmJ1Rg-JyLxYfp3o61zU?rlkey=kln78khkfi6gzj7ax09qfewtx&st=tn1ak5yy&dl=0' WHERE name = '65FT VIKING';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/zb9cypo22xq9rnchaogbt/AAqa2FJcp3hEY6Ivr9X8wDQ?rlkey=h25yapafw1hvcmt52u8ufaepy&st=1i0nulq4&dl=0' WHERE name = '40FT AXOPAR “CANELO BOXER YACHT”';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/6ig68cla1ytz96guvthjh/AA-IZVlMpfzW_NU6RjEZvXo?rlkey=v9dqoec78j1ef3ge3koiigqjy&st=wwlhj9w1&dl=0' WHERE name = '42FT DORAL HAWAII';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/p45t6pwxac7sv4jq43iz4/AApDhaxSc9GgzzOaVlKVsQM?rlkey=tvccikvdhe9iskfezi5ibqv0l&st=cm2ow4su&dl=0' WHERE name = '60FT SUNSEEKER PREDATOR';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/1utztplf7n3lzausb4sdy/AGxEYuPJghM9IJ4ugi-alN8?rlkey=51sxws74ohlaswrg9omaozagk&e=1&st=q7r7rdua&dl=0' WHERE name = '55FT Maxum - Exsea Mer';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1zAScbzWszWbsJEJWq0iFi72azoQhdd3t' WHERE name = '52FT The Ark, Beneteau Flybridge';
UPDATE boats SET photo_link = 'https://sfjetskirentals.com/jet-ski-rentals-page-jetski-delivery/' WHERE name = 'Jet Ski Rentals';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/07z97ghyyxslfqkqlfj8d/AOiOCWwlGzW3WjKcNVkYFhM?rlkey=qaitf5hkr3urhspanienwcdan&st=ws9o0m4j&dl=0' WHERE name = '120FT REX BAGLIETTO';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/qrgiparmlg6d8lzcswmir/AETDDDwZAYkwfPJhf4nUuLc?rlkey=1wcpv7urzae6kj805wgv07bzp&st=03j711z1&dl=0' WHERE name = '37FT MONTERREY WHITE';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1bH6b-6qGJ27o6ABXputjTLEmlNCp5dCY?usp=share_link' WHERE name = '55FT Azimut – “Azure”';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/mfkaa46zx5e6og1rbmvkb/ANbMAGPVMLKbjlsiex0-lQs?rlkey=htegpwjc4178g3blxcwfmg3w5&st=bzrc78of&dl=0' WHERE name = '40FT FORMULA';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/4jzxr5nmmqg5bqgg3ii2c/AHYgg0e4RB_YFb4otb2MF_0?rlkey=qbk5mo4obd6h2sk62xq0fbe0p&st=z0yurajp&dl=0' WHERE name = '45FT AZIMUT';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1K8vCjGAo0vDw1tiIRn8_QcYYXNpxsMt2?usp=sharing' WHERE name = '80FT UNIESE';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1nieQ3VIiGeY7JZIeHRvXW8hgKGKPPquf' WHERE name = '45FT SEA DAZE';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1CHirawdru52gxMynSSvqldjLOEGvWXIn?usp=sharing' WHERE name = '50FT SEA RAY';
UPDATE boats SET photo_link = 'https://arthurrender.smugmug.com/Duce-world-group-' WHERE name = '66FT Duce Marquis Sport';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/23znwa1xh62qgzhpxhara/AKItW6GJYZb4OQlHMuUysGQ?rlkey=cgntcr9ookcv2isz2w2h5q53u&st=5v2sp2v2&dl=0' WHERE name = '40FT Sea Ray Seacrecy';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/zs3p18a1kqtxgfn08dkd0/AHJCshJe08x06_mCvyCiGT0?rlkey=3ju3zaehoyxlm4s7l0t3ipvzd&st=7t7ir6nz&dl=0' WHERE name = '48FT SILVERTON SPORT BRIDGE';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/cv6bape1scu0bab6jwmmy/ALYDCEMC6UD47Hzk0mfZqKg?rlkey=t3qn0m5d5asdnypkj53t1pys9&e=1&st=yksjs1xs&dl=0' WHERE name = '29FT HURRICANE';
UPDATE boats SET photo_link = 'https://yachtscollection.pixieset.com/azimut65sealavie/' WHERE name = '65FT Azimut Sea La Vie';
UPDATE boats SET photo_link = 'https://photos.app.goo.gl/XPAAZHUUpY9bLsUE7' WHERE name = '60FT Fairline Flybridge Catalaya';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/nl4frf5o3rhfbodr1nlrh/AKxnp8mjmlfLwU8dPLDb-SA?rlkey=wg74v18pcdl3gzplih4lkzalo&e=1&st=t4px3y9z&dl=0' WHERE name = '42FT “PINK GUN"';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1-3eknchs3x_p0keaxt04ViHkoxSuGDOF' WHERE name = '42FT Sea Ray Havenly';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/12m2ECa7h67RliPctxMHhNEAoTlMjAHna' WHERE name = '60FT AZIMUT "A"';
UPDATE boats SET photo_link = 'https://photos.google.com/share/AF1QipOZBQuYrhUJB_nbGiYQiBc2uYaJuVyWoB6MkWnb_OR9eOI6_7VVdVz6_YWf8xIX9w?key=SnhMcDAxdk1Kd1ozYlljOEhzUVJCOXpfMjVPWHN3' WHERE name = '50FT Cruiser “Bella Vita”';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/ad1kpprj7mh05xr4yt4qn/ACOLmmBcyRN1W9UQgKdoLrM?rlkey=spcgcxl6m8c5al026aen53nuj&st=c42mpmj5&dl=0' WHERE name = '64FT PERSHING';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/b4bolnirvqyv6a06sdlqv/h?rlkey=vz784n2qp98tg9hiy474o5nsf&st=peqof5ou&dl=0' WHERE name = '90FT AZIMUT';
UPDATE boats SET photo_link = 'https://photos.app.goo.gl/XPAAZHUUpY9bLsUE7' WHERE name = '60FT Fairline Flybridge Catalaya';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1SJ9aN7D4WwWcw-UPlrtETIqwHOiE-ozO' WHERE name = '50FT Remedy Cruiser Sport Fly Bridge';
UPDATE boats SET photo_link = 'https://photos.app.goo.gl/XPAAZHUUpY9bLsUE7' WHERE name = '60FT Fairline Flybridge Catalaya';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/ciun0gc8i5pim6xb0jqtz/AFU7tL6A3iO6Ari1V1-nCYM?rlkey=jm7vykr26jl6vn18nd40c0vfa&st=xij8n43p&dl=0' WHERE name = '36FT REGAL';
UPDATE boats SET photo_link = 'https://floridalistingmedia.smugmug.com/YachtPhotographyGallery/n-dWL8QL/100-Azimut-Jumbo' WHERE name = '100FT DANIELA AZIMUT JUMBO';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1yRTLnai8kPA3aCbEoR927QD-QswRjzEU' WHERE name = '55FT Summer Girl, Cruiser Sport';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/dffizk7hfhz0t6vo4602k/ABOh3X03lVSxn3n2Vo2NsXk?rlkey=r6z17z8xihymkqg5p12j67kav&st=sk9l9xxv&dl=0' WHERE name = '110FT DOMINATOR';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/yclcukcpxz07obr8hk79p/AEA2ExJejp8IEYucum1MsD4?rlkey=yggz5s41q8hwk1w2wgs7bhgzh&st=qqkvrydi&dl=0' WHERE name = '45FT TEMPEST';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/12FWdeZXlZjbhKMhAuW2GYge4n9V_HU7E' WHERE name = '50FT Viking Enterprise';
UPDATE boats SET photo_link = 'https://www.dropbox.com/scl/fo/osbehzbjlfw9s0d335cug/AEygg_EWJVs24xMKbyCz1eQ?rlkey=6g77k748smar1cllo6j9xio12&st=zu0d6u6n&dl=0' WHERE name = '37FT CRUISER MIAMI';
UPDATE boats SET photo_link = 'https://drive.google.com/drive/folders/1IoZsHGBirvhadR5feTG2Ew5IqMolYWib' WHERE name = '60FT SEA RAY JET SET';

